///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest22
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest22Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1ba423b5-8d9e-4c79-8fed-b0add70c416f")]
    public partial class MyTest22Repository : RepoGenBaseFolder
    {
        static MyTest22Repository instance = new MyTest22Repository();
        MyTest22RepositoryFolders.TestAutomationForGUITestingRanoreAppFolder _testautomationforguitestingranore;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest22Repository element repository.
        /// </summary>
        [RepositoryFolder("1ba423b5-8d9e-4c79-8fed-b0add70c416f")]
        public static MyTest22Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest22Repository() 
            : base("MyTest22Repository", "/", null, 0, false, "1ba423b5-8d9e-4c79-8fed-b0add70c416f", ".\\RepositoryImages\\MyTest22Repository1ba423b5.rximgres")
        {
            _testautomationforguitestingranore = new MyTest22RepositoryFolders.TestAutomationForGUITestingRanoreAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1ba423b5-8d9e-4c79-8fed-b0add70c416f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanore folder.
        /// </summary>
        [RepositoryFolder("fd736a58-e500-4d56-b462-6faa45446063")]
        public virtual MyTest22RepositoryFolders.TestAutomationForGUITestingRanoreAppFolder TestAutomationForGUITestingRanore
        {
            get { return _testautomationforguitestingranore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest22RepositoryFolders
    {
        /// <summary>
        /// The TestAutomationForGUITestingRanoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("fd736a58-e500-4d56-b462-6faa45446063")]
        public partial class TestAutomationForGUITestingRanoreAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productsInfo;
            RepoItemInfo _guitestingInfo;

            /// <summary>
            /// Creates a new TestAutomationForGUITestingRanore  folder.
            /// </summary>
            public TestAutomationForGUITestingRanoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestAutomationForGUITestingRanore", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "fd736a58-e500-4d56-b462-6faa45446063", "")
            {
                _productsInfo = new RepoItemInfo(this, "Products", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Products']", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Products']", 30000, null, "b54dd2af-10ba-4aa4-bd87-9b753cbf322e");
                _guitestingInfo = new RepoItemInfo(this, "GUITesting", ".//div[#'menu_prod_en']/div[@id='et-boc']/div/div/div/div[1]/div[1]/div[2]/?/?/ul/li[2]/a[@innertext='GUI Testing']", ".//div[#'menu_prod_en']//a[@innertext='GUI Testing']", 30000, null, "5f3138b5-f171-489c-b952-ec2b13de96ee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd736a58-e500-4d56-b462-6faa45446063")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd736a58-e500-4d56-b462-6faa45446063")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Products item.
            /// </summary>
            [RepositoryItem("b54dd2af-10ba-4aa4-bd87-9b753cbf322e")]
            public virtual Ranorex.ATag Products
            {
                get
                {
                    return _productsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Products item info.
            /// </summary>
            [RepositoryItemInfo("b54dd2af-10ba-4aa4-bd87-9b753cbf322e")]
            public virtual RepoItemInfo ProductsInfo
            {
                get
                {
                    return _productsInfo;
                }
            }

            /// <summary>
            /// The GUITesting item.
            /// </summary>
            [RepositoryItem("5f3138b5-f171-489c-b952-ec2b13de96ee")]
            public virtual Ranorex.ATag GUITesting
            {
                get
                {
                    return _guitestingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GUITesting item info.
            /// </summary>
            [RepositoryItemInfo("5f3138b5-f171-489c-b952-ec2b13de96ee")]
            public virtual RepoItemInfo GUITestingInfo
            {
                get
                {
                    return _guitestingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
